window.GAMES_LIBRARY = window.GAMES_LIBRARY || [];
window.GAMES_LIBRARY.push({
  id:'chain-game',
  name:'Chain Game',
  mechanic:'word',
  format:'Set the player count above - a fresh word chain is drawn for each player at the start of a round. The current player types the next link into the box themselves; the app checks it against the real answer. A correct guess reveals the word and moves to the next link; a wrong guess shows the real answer and passes to the next player. The round ends once everyone has had a turn - New Round then draws a fresh set of chains.',
  usesPlayers:true,
  summary:'Each player types their own word chain link by link, checked automatically, until they miss.',
  pools:[
    { title:'All chains', subtitle:'32 chains total', items:[
      {name:'red -> hot -> dog -> park -> bench -> press -> conference -> room -> service -> animal'},
      {name:'school -> bus -> stop -> watch -> tower -> bridge -> water -> bottle -> rocket -> science'},
      {name:'picnic -> basket -> ball -> game -> show -> time -> machine -> shop -> owner -> manual'},
      {name:'ice -> cream -> cheese -> cake -> walk -> through -> line -> drive -> way -> finder'},
      {name:'fire -> truck -> stop -> sign -> language -> barrier -> reef -> shark -> tank -> top'},
      {name:'snow -> ball -> pit -> crew -> cut -> scene -> partner -> dance -> floor -> plan'},
      {name:'sun -> screen -> door -> bell -> pepper -> spray -> paint -> brush -> fire -> drill'},
      {name:'star -> fish -> tank -> engine -> block -> party -> favor -> item -> shop -> class'},
      {name:'moon -> light -> house -> plant -> food -> truck -> bed -> frame -> rate -> card'},
      {name:'book -> shelf -> life -> jacket -> pocket -> watch -> list -> price -> tag -> team'},
      {name:'rain -> coat -> check -> point -> guard -> dog -> house -> key -> lime -> wire'},
      {name:'stone -> wall -> street -> race -> track -> suit -> case -> study -> hall -> pass'},
      {name:'coffee -> table -> tennis -> shoe -> lace -> curtain -> call -> center -> field -> trip'},
      {name:'brain -> storm -> drain -> pipe -> dream -> team -> spirit -> week -> night -> shift'},
      {name:'video -> game -> plan -> B -> movie -> star -> chart -> topper -> hat -> trick'},
      {name:'power -> line -> judge -> jury -> duty -> free -> throw -> blanket -> statement -> piece'},
      {name:'phone -> case -> file -> cabinet -> maker -> space -> bar -> code -> red -> carpet'},
      {name:'mail -> box -> office -> chair -> lift -> ticket -> stub -> toe -> ring -> leader'},
      {name:'laser -> tag -> sale -> pitch -> black -> tie -> game -> face -> mask -> slip'},
      {name:'camp -> fire -> escape -> room -> temperature -> check -> mark -> down -> payment -> plan'},
      {name:'sun -> flower -> pot -> hole -> punch -> line -> dance -> floor -> plan -> B'},
      {name:'water -> fall -> out -> line -> up -> stairs -> case -> study -> group -> chat'},
      {name:'play -> ground -> work -> out -> line -> backer -> yard -> sale -> price -> tag'},
      {name:'black -> board -> game -> plan -> B -> movie -> star -> light -> house -> keeper'},
      {name:'home -> work -> shop -> lift -> off -> line -> up -> town -> house -> keeper'},
      {name:'light -> house -> hold -> up -> town -> ship -> wreck -> age -> old -> school'},
      {name:'back -> pack -> age -> group -> chat -> room -> service -> desk -> job -> title'},
      {name:'sun -> screen -> play -> ground -> work -> out -> break -> fast -> food -> truck'},
      {name:'door -> bell -> pepper -> corn -> field -> trip -> wire -> tap -> dance -> floor'},
      {name:'rain -> bow -> tie -> break -> down -> town -> house -> hold -> up -> town'},
      {name:'book -> case -> study -> hall -> way -> side -> walk -> through -> out -> side'},
      {name:'moon -> light -> house -> plant -> food -> truck -> stop -> watch -> dog -> house'}
    ]}
  ]
});
