window.GAMES_LIBRARY = window.GAMES_LIBRARY || [];
window.GAMES_LIBRARY.push({
  id:'headbandz',
  name:'Headbandz',
  mechanic:'word',
  format:'2 names per board',
  summary:'Draw two random names from one large category of 100 famous people.',
  notes:[
    'There is only one category now, so New names always stays within the same famous-people pool.',
    'The site shows only two names at a time for the current round.',
    'Use the New names button to redraw two different names from the same 100-person list.'
  ],
  pools:[
    { title:'100 famous people', subtitle:'Draw two random names from this pool', items:[
      {name:'Tom Hanks', detail:'Actor'},
      {name:'Meryl Streep', detail:'Actor'},
      {name:'Leonardo DiCaprio', detail:'Actor'},
      {name:'Julia Roberts', detail:'Actor'},
      {name:'Denzel Washington', detail:'Actor'},
      {name:'Jennifer Lawrence', detail:'Actor'},
      {name:'Brad Pitt', detail:'Actor'},
      {name:'Angelina Jolie', detail:'Actor'},
      {name:'Morgan Freeman', detail:'Actor'},
      {name:'Scarlett Johansson', detail:'Actor'},
      {name:'George Clooney', detail:'Actor'},
      {name:'Nicole Kidman', detail:'Actor'},
      {name:'Robert Downey Jr.', detail:'Actor'},
      {name:'Emma Stone', detail:'Actor'},
      {name:'Keanu Reeves', detail:'Actor'},
      {name:'Sandra Bullock', detail:'Actor'},
      {name:'Tom Cruise', detail:'Actor'},
      {name:'Kate Winslet', detail:'Actor'},
      {name:'Will Smith', detail:'Actor'},
      {name:'Natalie Portman', detail:'Actor'},
      {name:'Barack Obama', detail:'Politician'},
      {name:'Donald Trump', detail:'Politician'},
      {name:'Joe Biden', detail:'Politician'},
      {name:'Kamala Harris', detail:'Politician'},
      {name:'Hillary Clinton', detail:'Politician'},
      {name:'Bernie Sanders', detail:'Politician'},
      {name:'Mitt Romney', detail:'Politician'},
      {name:'Nancy Pelosi', detail:'Politician'},
      {name:'Mitch McConnell', detail:'Politician'},
      {name:'Justin Trudeau', detail:'Politician'},
      {name:'Vladimir Putin', detail:'Politician'},
      {name:'Volodymyr Zelenskyy', detail:'Politician'},
      {name:'Emmanuel Macron', detail:'Politician'},
      {name:'Rishi Sunak', detail:'Politician'},
      {name:'Gavin Newsom', detail:'Politician'},
      {name:'Alexandria Ocasio-Cortez', detail:'Politician'},
      {name:'George W. Bush', detail:'Politician'},
      {name:'Hakeem Jeffries', detail:'Politician'},
      {name:'Nancy Mace', detail:'Politician'},
      {name:'Michelle Obama', detail:'Public figure'},
      {name:'Oprah Winfrey', detail:'Media'},
      {name:'Beyonce', detail:'Singer'},
      {name:'Taylor Swift', detail:'Singer'},
      {name:'Rihanna', detail:'Singer'},
      {name:'Adele', detail:'Singer'},
      {name:'Drake', detail:'Artist'},
      {name:'Ed Sheeran', detail:'Singer'},
      {name:'Bruno Mars', detail:'Singer'},
      {name:'Bono', detail:'Singer'},
      {name:'Lady Gaga', detail:'Singer'},
      {name:'Elon Musk', detail:'Business'},
      {name:'Jeff Bezos', detail:'Business'},
      {name:'Bill Gates', detail:'Business'},
      {name:'Mark Zuckerberg', detail:'Business'},
      {name:'Warren Buffett', detail:'Business'},
      {name:'Steve Jobs', detail:'Business'},
      {name:'Tim Cook', detail:'Business'},
      {name:'Sam Altman', detail:'Business'},
      {name:'Sundar Pichai', detail:'Business'},
      {name:'Satya Nadella', detail:'Business'},
      {name:'Tiger Woods', detail:'Athlete'},
      {name:'LeBron James', detail:'Athlete'},
      {name:'Lionel Messi', detail:'Athlete'},
      {name:'Serena Williams', detail:'Athlete'},
      {name:'Michael Jordan', detail:'Athlete'},
      {name:'Tom Brady', detail:'Athlete'},
      {name:'Stephen Curry', detail:'Athlete'},
      {name:'Cristiano Ronaldo', detail:'Athlete'},
      {name:'Simone Biles', detail:'Athlete'},
      {name:'Naomi Osaka', detail:'Athlete'},
      {name:'Ellen DeGeneres', detail:'Media'},
      {name:'David Letterman', detail:'Media'},
      {name:'Jimmy Fallon', detail:'Media'},
      {name:'Stephen Colbert', detail:'Media'},
      {name:'Ryan Reynolds', detail:'Actor'},
      {name:'Hugh Jackman', detail:'Actor'},
      {name:'Chris Hemsworth', detail:'Actor'},
      {name:'Chris Evans', detail:'Actor'},
      {name:'Ariana Grande', detail:'Singer'},
      {name:'Selena Gomez', detail:'Singer'},
      {name:'Justin Bieber', detail:'Singer'},
      {name:'Katy Perry', detail:'Singer'},
      {name:'Shakira', detail:'Singer'},
      {name:'Bad Bunny', detail:'Singer'},
      {name:'The Weeknd', detail:'Singer'},
      {name:'Billie Eilish', detail:'Singer'},
      {name:'Post Malone', detail:'Artist'},
      {name:'Harry Styles', detail:'Singer'},
      {name:'Miley Cyrus', detail:'Singer'},
      {name:'Jennifer Lopez', detail:'Singer'},
      {name:'Alicia Keys', detail:'Singer'},
      {name:'Zac Efron', detail:'Actor'},
      {name:'Emma Watson', detail:'Actor'},
      {name:"Lupita Nyong'o", detail:'Actor'},
      {name:'Jennifer Aniston', detail:'Actor'},
      {name:'Dwayne Johnson', detail:'Actor'},
      {name:'Chris Pratt', detail:'Actor'},
      {name:'Robert De Niro', detail:'Actor'},
      {name:'Samuel L. Jackson', detail:'Actor'},
      {name:'Harrison Ford', detail:'Actor'}
    ]}
  ]
});